---
title: passiondoiseaux
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: passiondoiseaux
description:  Passion d'oiseaux page dédié aux plumes qui chantent, une œuvre de Guy Vandelaer.
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
twitter_username: Blindhelp38
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: BlindHelp
  instagram: 
  linkedin: 
  pinterest: 
  rss: https://blindhelp.github.io/passiondoiseaux/feed.xml
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: 
baseurl: 'https://blindhelp.github.io/passiondoiseaux'
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile.lock
- LICENSE
- README.md
- CNAME
authors:
  passiondoiseaux:
    name: passiondoiseaux
    display_name: passiondoiseaux
    web: https://blindhelp.github.io/passiondoiseaux
issues_repo: BlindHelp/passiondoiseaux